version: '2.29.0'
services:
    db:
        image: postgres
        container_name: postgree-db
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: keycloakdb
            POSTGRES_USER: keycloakusr
            POSTGRES_PASSWORD: keycloakusr        
        networks:
            app-network:
                ipv4_address: 10.5.0.2
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U keycloakusr -d keycloakdb"]
            interval: 5s
            timeout: 10s
            retries: 10

    keycloak:
        depends_on:
            db:
                condition: service_healthy
        image: quay.io/keycloak/keycloak:25.0.2
        restart: always
        container_name: keycloak-app
        command: ["start-dev", "--import-realm", "--dir=/opt/keycloak/data/import"]
        ports:
            - 8080:8080
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: postgres
            KC_DB_USERNAME: keycloakusr
            KC_DB_PASSWORD: keycloakusr
            KC_DB_URL: jdbc:postgresql://10.5.0.2:5432/keycloakdb
        volumes:
            - "./config:/opt/keycloak/data/import"
        networks:
            app-network:
                ipv4_address: 10.5.0.3
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

networks:
    app-network:
        driver: bridge
        ipam:
            config:
              - subnet: 10.5.0.0/16
                gateway: 10.5.0.1
